FROM ubuntu:16.04
COPY . /app
RUN chmod -R -x /app/janus-gateway
WORKDIR /app
RUN apt-get update && apt-get install -y \
    libjansson-dev \
    libnice-dev \
    libglib2.0-dev \
    pkg-config \
    gengetopt \
    libtool \
    automake \
    wget \
    git \
    libssl-dev \
    cmake \
    && rm -rf /var/lib/apt/lists/* \

    #Install Libsrtp

    && mkdir libsrtp && cd libsrtp \
    && wget https://github.com/cisco/libsrtp/archive/v1.5.4.tar.gz \
    && tar xfv v1.5.4.tar.gz \
    && cd libsrtp-1.5.4 \
    && ./configure --prefix=/usr --enable-openssl \
    && make shared_library && make install \
    && cd /app && rm -rf /app/libsrtp \

    #Install Janus

    && cd /app/janus-gateway && sh autogen.sh && ./configure --prefix=/opt/janus --disable-rabbitmq --disable-mqtt --disable-websockets --disable-unix-sockets --disable-sample-event-handler --disable-turn-rest-api --disable-plugin-audiobridge  --disable-plugin-recordplay --disable-plugin-sip --disable-plugin-videocall --disable-plugin-voicemail --disable-plugin-textroom \
    && make \
    && make install \
    && make configs \
    && cp /opt/janus/bin/janus /usr/local/bin

# Define the default start-up command
CMD janus
